import { useEffect, useState } from 'react';
import { Check, ChevronDown, ArrowLeft, ArrowUp, ArrowDown, PencilLine, Film, Loader2, Image as ImageIcon, Volume2, RefreshCw, Play, Pause } from 'lucide-react';
import RequirementCard from '../Generator/RequirementCard';
import GenerationPreferencePicker from '../Generator/GenerationPreferencePicker';
import { useVideoCoursewareStore } from '../../store/videoCoursewareStore';
import { useConversationStore } from '../../store/conversationStore';
import type { VideoProject, VideoSegment, MediaAsset } from '../../data/videoCourseware/model';
import { segmentLabels } from '../../data/videoCourseware/model';
import { VideoModal, AssetPreview, AudioPreview } from './Shared';
import VideoResourceEditor from './VideoResourceEditor';
import { ensureWorkflowMessage } from './workflow';

function SegmentEditor({project,segment,onClose}:{project:VideoProject;segment:VideoSegment;onClose:()=>void}){
 const [draft,setDraft]=useState({...segment});const update=useVideoCoursewareStore(s=>s.update);
 return <VideoModal title={`编辑环节 · ${segment.title}`} onClose={onClose}><div className="vc-form"><label>环节名称<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>内容形式<div className="vc-options">{(['video','mixed','h5'] as const).map(kind=><button className={draft.kind===kind?'selected':''} key={kind} onClick={()=>setDraft({...draft,kind,seconds:kind==='h5'?0:draft.seconds||6})}>{segmentLabels[kind]}</button>)}</div></label><label>教学内容<textarea value={draft.purpose} onChange={e=>setDraft({...draft,purpose:e.target.value})}/></label><label>学生如何参与<textarea value={draft.interaction} onChange={e=>setDraft({...draft,interaction:e.target.value})}/></label>{draft.kind!=='h5'&&<><label>画面和人物动作<textarea value={draft.visual} onChange={e=>setDraft({...draft,visual:e.target.value})}/></label><label>台词<textarea value={draft.dialogue} onChange={e=>setDraft({...draft,dialogue:e.target.value})}/></label><label>谁来说<div className="vc-options">{project.speakers.map(s=><button className={draft.speakerId===s.id?'selected':''} key={s.id} onClick={()=>setDraft({...draft,speakerId:s.id})}>{s.name}</button>)}</div></label><label>预计视频时长（秒）<input type="number" min={3} max={60} value={draft.seconds} onChange={e=>setDraft({...draft,seconds:Number(e.target.value)})}/></label></>}<label>怎样进入下一环节<textarea value={draft.next} onChange={e=>setDraft({...draft,next:e.target.value})}/></label></div><p className="vc-hint">这里修改教学方案。确认后，会据此准备图片、配音和视频。</p><footer className="vc-actions"><button className="vc-btn" onClick={onClose}>取消</button><button className="vc-btn primary" disabled={!draft.title.trim()||!draft.purpose.trim()} onClick={()=>{update(project.id,{segments:project.segments.map(s=>s.id===draft.id?draft:s),pendingEdit:`调整“${draft.title}”`});onClose();}}>保存修改</button></footer></VideoModal>;
}
function PlanContents({project,readOnly}:{project:VideoProject;readOnly:boolean}){
 const [editing,setEditing]=useState<VideoSegment|null>(null),[expanded,setExpanded]=useState(false);const update=useVideoCoursewareStore(s=>s.update);const shown=expanded?project.segments:project.segments.slice(0,5);
 function move(id:string,delta:number){const next=[...project.segments],index=next.findIndex(s=>s.id===id);[next[index],next[index+delta]]=[next[index+delta],next[index]];update(project.id,{segments:next,pendingEdit:'调整环节顺序'});}
 return <><div className="vc-plan-summary"><span><Film size={15}/>视频用于{project.videoUse}</span><span>{project.segments.filter(s=>s.kind!=='h5').length} 段视频 · 约 {Math.round(project.segments.reduce((n,s)=>n+s.seconds,0))} 秒</span></div><div className="vc-segments">{shown.map((s,i)=><div className="vc-segment" key={s.id}><span className="vc-order">{i+1}</span><div className="vc-segment-copy"><div><b>{s.title}</b><span className="vc-kind">{segmentLabels[s.kind]}</span></div><p>{s.purpose}</p><small>{s.kind==='h5'?'由学生操作推进':`视频约 ${s.seconds} 秒`} · {s.next}</small></div>{!readOnly&&<div className="vc-segment-actions"><button className="vc-btn edit" onClick={()=>setEditing(s)}><PencilLine size={13}/>编辑</button><button className="vc-icon" aria-label={`上移${s.title}`} disabled={i===0} onClick={()=>move(s.id,-1)}><ArrowUp size={13}/></button><button className="vc-icon" aria-label={`下移${s.title}`} disabled={i===project.segments.length-1} onClick={()=>move(s.id,1)}><ArrowDown size={13}/></button></div>}</div>)}</div>{project.segments.length>5&&<button className="vc-text-btn" onClick={()=>setExpanded(!expanded)}>{expanded?'收起环节':`展开全部 ${project.segments.length} 个环节`}<ChevronDown size={14}/></button>}<p className="vc-hint">视频时长只计算观看部分。认读、操作和答题会等待学生完成。</p>{editing&&<SegmentEditor project={project} segment={editing} onClose={()=>setEditing(null)}/>}</>;
}
function SpeakerSettings({project,readOnly=false}:{project:VideoProject;readOnly?:boolean}){
 const update=useVideoCoursewareStore(s=>s.update);
 return <section className="vc-speakers"><h3><Volume2 size={16}/>旁白和角色配音</h3><p className="vc-hint">旁白负责讲解与读题；有台词的人物分别使用自己的声音。</p>{project.speakers.map(s=><div className="vc-speaker" key={s.id}><div><b>{s.name}</b><small>{s.role==='narrator'?'讲解、读题与反馈':'角色对白与行动邀请'}</small></div>{readOnly?<span>{s.voiceName}</span>:<GenerationPreferencePicker controls="voice" showMode={false} value={{voiceMode:'manual',voiceName:s.voiceName,voiceId:s.voiceId,voiceLanguage:s.voiceLanguage||(project.subject==='英语'?'英语-英音':'中文')}} onChange={value=>update(project.id,{speakers:project.speakers.map(x=>x.id===s.id?{...x,voiceName:value.voiceName||'智能匹配',voiceId:value.voiceId,voiceLanguage:value.voiceLanguage}:x),pendingEdit:`调整${s.name}的声音`})}/>}</div>)}</section>;
}
function GenerationProgress({project}:{project:VideoProject}){
 const [clock,setClock]=useState(()=>Date.now());useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),180);return()=>clearInterval(timer);},[]);
 const store=useVideoCoursewareStore(),job=project.job;
 const ratio=job?Math.min(1,((['paused','failed'].includes(project.phase)?0:clock-job.start)+job.elapsed)/job.duration):1;
 const isAssets=job?.kind==='assets',isAssembly=job?.kind==='assembly',isPlan=job?.kind==='plan';
 const title=isPlan?'正在整理教学方案':isAssets?'正在生成图片和配音':isAssembly?'正在生成互动页面，衔接完整课件':'正在生成视频';
 const relevant=project.assets.filter(a=>isAssets?a.kind!=='video':a.kind==='video');
 const ready=relevant.filter(a=>project.readyAssetIds.includes(a.id)).length;
 return <section className="vc-card vc-progress" aria-live="polite"><header><h3>{['paused','failed'].includes(project.phase)?<Pause size={17}/>:<Loader2 size={17} className="vc-spin"/>}{project.phase==='paused'?'生成已暂停':project.phase==='failed'?'部分内容生成失败':title}</h3><span>{Math.round(ratio*100)}%</span></header><div className="vc-progress-track"><i style={{width:`${ratio*100}%`}}/></div><p>{isPlan?'正在理解材料、教学目标，并安排视频与互动的顺序。':isAssets?'先准备角色、场景与关键画面，同时按旁白和角色分别生成配音。':isAssembly?'正在接入视频、教学文字与操作反馈，让每个环节自然衔接。':'根据已确认的图片和配音逐段生成。已完成的片段会保留，你可以先查看。'}</p>{!isPlan&&!isAssembly&&<div className="vc-job-counts"><span><Check size={14}/>已完成 {ready} / {relevant.length} {isAssets?'项素材':'个视频片段'}</span>{isAssets&&<span>图片 {relevant.filter(a=>a.kind==='image'&&project.readyAssetIds.includes(a.id)).length} / {relevant.filter(a=>a.kind==='image').length} · 配音 {relevant.filter(a=>a.kind==='audio'&&project.readyAssetIds.includes(a.id)).length} / {relevant.filter(a=>a.kind==='audio').length} 条</span>}</div>}{project.error&&<p className="vc-error">{project.error}</p>}<footer className="vc-actions">{project.phase==='paused'||project.phase==='failed'?<><button className="vc-btn" onClick={()=>store.update(project.id,{phase:'plan',job:undefined})}><ArrowLeft size={14}/>返回方案</button><button className="vc-btn primary" onClick={()=>store.resume(project.id)}><RefreshCw size={14}/>{project.phase==='failed'?'仅重试未完成内容':'继续生成'}</button></>:!isPlan&&<button className="vc-text-btn" onClick={()=>store.pause(project.id)}>暂停生成</button>}</footer></section>;
}
function AssetReview({project}:{project:VideoProject}){
 const [tab,setTab]=useState<'image'|'audio'|'video'>('image'),[viewing,setViewing]=useState<MediaAsset|null>(null),[edit,setEdit]=useState(false);const store=useVideoCoursewareStore();
 const showVideos=['video-loading','assembling','ready'].includes(project.phase)||(project.phase==='paused'&&project.job?.kind==='video');
 const items=project.assets.filter(a=>a.kind===tab);
 const loading=project.job?.kind==='assets';
 return <section className="vc-card"><header className="vc-card-header"><div><h3>{showVideos?'课件素材':loading?'图片与配音':'确认画面与配音'}</h3><p>{showVideos?'可查看已完成的内容，其他内容会继续生成。':loading?'素材会陆续出现在这里，全部完成后可以集中确认。':'图片和配音已生成。先看形象与场景、听人物和旁白，合适后再生成视频。'}</p></div><button className="vc-btn" disabled={!project.readyAssetIds.length} onClick={()=>setEdit(true)}><PencilLine size={14}/>编辑资源</button></header><div className="vc-tabs" role="tablist" aria-label="素材类型">{(['image','audio',...(showVideos?['video']:[])] as const).map(kind=><button role="tab" aria-selected={tab===kind} key={kind} className={tab===kind?'active':''} onClick={()=>setTab(kind as typeof tab)}>{kind==='image'?<ImageIcon size={16}/>:kind==='audio'?<Volume2 size={16}/>:<Film size={16}/ >}{kind==='image'?'图片':kind==='audio'?'配音':'视频'} <span>{project.assets.filter(a=>a.kind===kind).length}</span></button>)}</div>{tab==='audio'?<div className="vc-audio-groups">{project.speakers.map(s=><section key={s.id}><h4>{s.name}<small>{s.voiceName}</small></h4><div className="vc-speaker-clips">{items.filter(a=>a.speakerId===s.id).map(a=><div className="vc-audio-item" key={a.id}><div><b>{a.name}</b><p>{a.text}</p></div><AudioPreview url={project.readyAssetIds.includes(a.id)?a.url:undefined}/></div>)}</div></section>)}</div>:<div className="vc-asset-grid">{items.map(a=><button className="vc-asset" key={a.id} disabled={!project.readyAssetIds.includes(a.id)} onClick={()=>setViewing(a)}>{project.readyAssetIds.includes(a.id)?<><img src={a.poster||a.url} alt={a.name}/>{a.kind==='video'&&<Play className="vc-play-overlay" size={25}/>}</>:<div className="vc-media-placeholder"><Loader2 className="vc-spin" size={20}/><span>生成中</span></div>}<b>{a.name}</b><small>{a.kind==='video'?`${a.seconds} 秒`:a.role}</small></button>)}</div>}{project.phase==='assets-review'&&<footer className="vc-actions"><button className="vc-btn" onClick={()=>{store.update(project.id,{phase:'plan'});requestAnimationFrame(()=>document.querySelector(`[data-video-plan="${project.id}"]`)?.scrollIntoView({behavior:'smooth',block:'start'}));}}><ArrowLeft size={14}/>返回修改方案</button><button className="vc-btn primary" onClick={()=>{useConversationStore.getState().addUserMessage(project.conversationId,'画面和配音已确认，开始生成视频。');useConversationStore.getState().setWaitingForUserAction(project.conversationId,false);ensureWorkflowMessage(project,'production');store.start(project.id,'video');}}>画面与配音确认，生成视频</button></footer>}{viewing&&<VideoModal title={viewing.name} onClose={()=>setViewing(null)}><AssetPreview asset={viewing}/><p className="vc-hint">使用位置：{viewing.segmentIds.map(id=>project.segments.find(s=>s.id===id)?.title).filter(Boolean).join('、')}</p><details className="vc-details"><summary>查看生成描述</summary><pre>{viewing.prompt}</pre></details></VideoModal>}{edit&&<VideoResourceEditor projectId={project.id} onClose={()=>setEdit(false)}/>}</section>;
}
export default function VideoWorkflowCard({projectId,stage='plan'}:{projectId:string;stage?:'plan'|'assets'|'production'}){
 const project=useVideoCoursewareStore(s=>s.projects[projectId]);const store=useVideoCoursewareStore();const [expanded,setExpanded]=useState(false);
 if(!project)return null;
 if(stage==='plan'){
  if(project.phase==='planning')return <GenerationProgress project={project}/>;
  const editable=project.phase==='plan';
  return <div className="vc-workflow" data-video-plan={project.id}><RequirementCard framework={project.framework} readOnly={!editable} onFrameworkChange={framework=>store.update(project.id,{framework,pendingEdit:'调整教学方案'})} featureContent={<PlanContents project={project} readOnly={!editable}/>}><SpeakerSettings project={project} readOnly={!editable}/>{editable&&<p className="vc-hint">确认后先生成图片与配音；你可以试听、修改，再开始生成视频。</p>}</RequirementCard>{editable&&<div className="vc-confirm-action"><button className="vc-btn primary" disabled={!project.framework.userRequirement.trim()} onClick={()=>{useConversationStore.getState().addUserMessage(project.conversationId,'确认需求，开始生成图片和配音。');ensureWorkflowMessage(project,'assets');useConversationStore.getState().setWaitingForUserAction(project.conversationId,false);store.start(project.id,'assets');}}>确认需求，开始生成</button></div>}</div>;
 }
 if(project.phase==='plan'||project.phase==='planning')return null;
 const active=stage==='assets'?project.phase==='assets-review'||project.job?.kind==='assets':project.job?.kind==='video'||project.job?.kind==='assembly';
 return <div className="vc-workflow">{active?<>{project.job&&<GenerationProgress project={project}/>}<AssetReview project={project}/></>:<><button className="vc-history-summary" onClick={()=>setExpanded(!expanded)}><Check size={17}/><span>{stage==='assets'?'图片和配音已确认':'视频与互动课件已生成'}</span><ChevronDown size={15}/></button>{expanded&&<AssetReview project={project}/>}</>}</div>;
}
